version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  order-api:
    build: ./order-api
    ports:
      - "5000:80"
    depends_on:
      - inventory-api
      - billing-api
      - shipping-api

  inventory-api:
    build: ./inventory-api
    ports:
      - "6001:80"

  billing-api:
    build: ./billing-api
    ports:
      - "6002:80"

  shipping-api:
    build: ./shipping-api
    ports:
      - "6003:80"

  order-processor:
    build: ./order-processor
    ports:
      - "6000:80"
