apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "${SERVICEBUS_CONNECTION_STRING}"
  - name: topic
    value: orders
  - name: subscriptionName
    value: processor