apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order-processor"
        dapr.io/app-port: "6000"
    spec:
      containers:
      - name: order-processor
        image: order-processor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
